Add the ability to update profile picture and display name
Gauravjeetsingh/gurmukhi-shabadavali pull request #1
Opened 2024-08-16 04:33 UTC by Gauravjeetsingh

Instead of a separate profile page, created a profile edit section right in the header, which appears right after clicking the display pic.

Limitations as of now:
- The dialog only closes if clicked on the profile picture, ideally it should close when clicked anywhere outside the section.
- The Edit/Logout button only have basic styles for now.
- We can't delete a profile picture, we can only change it.

https://github.com/user-attachments/assets/8cc60965-1811-4e46-843d-fb583a462eed

2024-08-18 22:47 UTC, gurjit03 requested changes
Great work ji 🔥 ! Some minor suggestions from myside.

2024-08-18 22:47 UTC, gurjit03 commented on src/components/authentication/AuthProvider.tsx
> +  setCurrentUser: Function;
@Gauravjeetsingh can do better at typing here.

2024-08-18 22:47 UTC, gurjit03 commented on src/components/common/CustomHeader.tsx
> +              onClick={() => setShowModal(!showModal)}
@Gauravjeetsingh This click function is bit confusing to whats it's doing.

2024-08-18 22:47 UTC, gurjit03 commented on src/components/common/CustomHeader.tsx
> +              {!currentUser.photoURL && currentUser.displayName?.charAt(0)}
@Gauravjeetsingh maybe lets create a variable.

2024-08-18 22:47 UTC, gurjit03 commented on src/components/common/ProfileSection.tsx
> +          console.log(currentUser);
@Gauravjeetsingh stale log

2024-08-18 22:47 UTC, gurjit03 commented on src/components/common/ProfileSection.tsx
> +        setEditMode(!editMode);
@Gauravjeetsingh would suggest to be explicit here rather than `negating variable`, for easier understanding.

2024-08-18 22:47 UTC, gurjit03 commented on src/components/common/utils/updateProfile.ts
> +  initialName: string | undefined;
@Gauravjeetsingh can opt for `initialName?: string`

2024-08-18 22:47 UTC, gurjit03 commented on src/components/common/utils/updateProfile.ts
> +  selectedFile: File | null;
@Gauravjeetsingh Why selectedFile is `null` while others are `undefined` ?

2024-08-20 03:50 UTC, Gauravjeetsingh commented on src/components/common/CustomHeader.tsx
> +              onClick={() => setShowModal(!showModal)}
It's toggling the modal state, that's all we needed to do on click. 

If showModal is true, on click it sets it to false, else sets it to true.

2024-08-20 03:52 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +  selectedFile: File | null;
If we dont select any file on clicking the input type file tag, the file instance it returns is null, instead of undefined.

2024-08-20 03:55 UTC, Gauravjeetsingh commented on src/components/common/CustomHeader.tsx
> +              {!currentUser.photoURL && currentUser.displayName?.charAt(0)}
Destructured the currentURL before the return statement, to get the photoURL and displayName

2024-08-20 03:57 UTC, Gauravjeetsingh commented on src/components/common/ProfileSection.tsx
> +          console.log(currentUser);
fixed

2024-08-20 04:00 UTC, Gauravjeetsingh commented on src/components/common/ProfileSection.tsx
> +        setEditMode(!editMode);
Um sure we can do that, any particular reason for not going with negating here?

2024-08-20 04:00 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +  initialName: string | undefined;
done

2024-08-20 04:00 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +  selectedFile: File | null;
Anyhow, if we use ?: like you said above, we dont have to mention undefined or null separately.

2024-08-20 06:45 UTC, gurjit03 commented on src/components/common/CustomHeader.tsx
> +              {!currentUser.photoURL && currentUser.displayName?.charAt(0)}
I mean for this whole, lets create a seperate variable`currentUser.displayName?.charAt(0)`

2024-08-20 06:46 UTC, gurjit03 commented on src/components/common/ProfileSection.tsx
> +        setEditMode(!editMode);
@Gauravjeetsingh for readability and better understanding. If I am reading the code from top to bottom, it's bit hard to remember the context - that which state the `editMode` is in. So rather than being in the `!editMode`, if we are sure we don't want that, better be `setEditModal(false)`. 
I hope this makes sense.

2024-08-20 06:47 UTC, gurjit03 commented on src/components/common/utils/updateProfile.ts
> +  selectedFile: File | null;
We don't have to specify undefined in that case. `Null` we still have to specify explicitely

2024-08-20 06:49 UTC, gurjit03 commented on src/components/common/utils/updateProfile.ts
> +  selectedFile?: File;
@Gauravjeetsingh We still have to explicitely mention about the `Null` here

2024-08-20 06:49 UTC, gurjit03 commented on src/components/common/CustomHeader.tsx
> +              onClick={() => setShowModal(!showModal)}
NIT 🌹: I would suggest in general to avoid this `!negation` logic, from code readability POV.

2024-08-20 15:57 UTC, Gauravjeetsingh commented on src/components/authentication/AuthProvider.tsx
> +  setCurrentUser: Function;
Fixed

2024-08-20 15:58 UTC, Gauravjeetsingh commented on src/components/common/CustomHeader.tsx
> +              {!currentUser.photoURL && currentUser.displayName?.charAt(0)}
We aren't using this anywhere else, so didn't use a variable here.

2024-08-20 15:59 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +  selectedFile: File | null;
Fixed.

2024-08-20 15:59 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +  selectedFile?: File;
Yeah, missed that, fixed now.

2024-08-20 16:10 UTC, Gauravjeetsingh commented on src/components/common/ProfileSection.tsx
> +        setEditMode(!editMode);
Yeah, makes sense, moved it to if-else statement we already had in this function.

2024-08-20 16:10 UTC, Gauravjeetsingh commented on src/components/common/CustomHeader.tsx
> +              onClick={() => setShowModal(!showModal)}
Let's keep this as it is for now, because its a simple logic, otherwise would have to add an if-else statement or a conditional operator here.

2024-08-20 16:13 UTC, Gauravjeetsingh commented
@gurjit03 veerji, thank you for the review, done with all the changes, merging this.

2024-08-20 16:13 UTC, merged