Add seed session and dashboard improvements
Gauravjeetsingh/gurmukhi-shabadavali pull request #3
Opened 2024-08-26 17:21 UTC by Gauravjeetsingh

- Starts a seed session
- Show a random word on page load
- Show nanak coins in header

2024-08-26 17:22 UTC, Gauravjeetsingh commented on src/components/game-session/GameSession.tsx
> +      console.log('session yet to generate');
Keeping this log here, as it is in progress, will complete that in next PRs

2024-08-31 22:56 UTC, gurjit03 requested changes

2024-08-31 22:56 UTC, gurjit03 commented on src/app/word/page.tsx
> +      <CustomFooter isSessionPage={false} />
NIT 🌹 should have been better to have isSessionPage default as false and passed if true.

2024-08-31 22:56 UTC, gurjit03 commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
@Gauravjeetsingh you can directly type the data here then we don't need to use any typecasting `as QuestionDataType`

2024-08-31 22:56 UTC, gurjit03 commented on src/components/common/CustomFooter.tsx
> +          <span key={index} className={getClassNames(index, currentQuestion)}>
@Gauravjeetsingh should add currentQuestion._id as key helpful in avoiding any potential bugs
https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318

2024-08-31 22:56 UTC, gurjit03 commented on src/components/dashboard/Dashboard.tsx
> +              {13 - currentSession[currentSlide]?.questionCount} Words
Where this magic number 13 is coming from :). Lets create an app level constant out of this !

2024-08-31 22:56 UTC, gurjit03 commented on src/components/game-session/Definition.tsx
> +        <p className="gurmukhi">{slide.data.meaning_punjabi}</p>
@Gauravjeetsingh lets focus on converting the this `meaning_punjabi` to JS standards for the variables.

2024-08-31 22:56 UTC, gurjit03 commented on src/components/game-session/Question.tsx
> +import { shuffleElements } from "./utils/shuffle";
@Gauravjeetsingh are we using this import?

2024-09-02 16:57 UTC, Gauravjeetsingh commented on src/app/word/page.tsx
> +      <CustomFooter isSessionPage={false} />
Fixed.

2024-09-02 17:02 UTC, Gauravjeetsingh commented on src/components/common/CustomFooter.tsx
> +          <span key={index} className={getClassNames(index, currentQuestion)}>
Good catch, updated the key property.

2024-09-02 17:03 UTC, Gauravjeetsingh commented on src/components/dashboard/Dashboard.tsx
> +              {13 - currentSession[currentSlide]?.questionCount} Words
Added to constant files.

2024-09-02 17:04 UTC, Gauravjeetsingh commented on src/components/game-session/Question.tsx
> +import { shuffleElements } from "./utils/shuffle";
Not right now, but we would in upcoming code, keeping this for now, will remove if not needed.

2024-09-02 18:28 UTC, gurjit03 commented on src/components/game-session/Question.tsx
> +import { shuffleElements } from "./utils/shuffle";
Thats upto you :), but as a general practice it's the other way around you require something when you actually needs it.

2024-09-02 20:54 UTC, Gauravjeetsingh commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
@gurjit03 veerji, didn't get this, where exactly are you referring to?

2024-09-02 20:55 UTC, Gauravjeetsingh commented on src/components/game-session/Question.tsx
> +import { shuffleElements } from "./utils/shuffle";
Yeah, i was using it initially, then removed it to test something else. I can remove for now, and we can readd when we use it.

2024-09-02 21:06 UTC, gurjit03 commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
@Gauravjeetsingh here
<img width="507" alt="image" src="https://github.com/user-attachments/assets/ccbc5fa8-8d5b-4da1-827e-2249262a483e">

2024-09-02 21:06 UTC, gurjit03 commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
so it should be `const currentSession = useAtomValue<QuestionType>(sessionAtom);`

2024-09-02 21:13 UTC, Gauravjeetsingh commented on src/components/game-session/Definition.tsx
> +        <p className="gurmukhi">{slide.data.meaning_punjabi}</p>
Done

2024-09-02 21:26 UTC, Gauravjeetsingh commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
The **sessionAtom** is an array of slides.
```export const sessionAtom = atomWithStorage<SessionData[] | []>('currentSession', []);```

And the **SessionData** is defined as
```export type SessionData = SentenceListDatatype | DefinitionDatatype | QuestionDatatype;```

The typecasting is done, only when the SessionData slide is a question.

2024-09-02 21:57 UTC, amitojsingh requested changes

2024-09-02 21:57 UTC, amitojsingh commented on package.json
> +    "jotai": "^2.9.3",
I am just curious why are we using Jotai? instead of redux, easy-peasy or react-query?

2024-09-02 21:57 UTC, amitojsingh commented on src/components/common/utils/updateProfile.ts
> +    console.error("Error uploading file", error);
can we remove console and use proper error handling like Bugsnag. We have Paid version of bugsnag which we can use.

2024-09-02 21:57 UTC, amitojsingh commented on src/components/dashboard/Dashboard.tsx
> +               to go for your next coin!
hard Coded Text can be removed.

2024-09-02 21:57 UTC, amitojsingh commented on src/components/game-session/Sentences.tsx
> +      <p>Examples</p>
Hard coded text :)

2024-09-02 21:58 UTC, amitojsingh commented
@Gauravjeetsingh can you grant me access to view the PR?

2024-09-02 22:09 UTC, gurjit03 commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
@Gauravjeetsingh I see thanks for explaining.

In that case I would use `typeGuard` rather than `type casting/assertion`

2024-09-02 22:16 UTC, gurjit03 commented on package.json
> +    "jotai": "^2.9.3",
Likewise @amitojsingh would like to hear more about this decision as I can mostly see the server data being used in the code.

2024-09-03 11:58 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +    console.error("Error uploading file", error);
Sure, I can integrate that in another PR. I was shying away from integrations until we have game sessions up and running.

There's one more PR after this, which includes the session creation part, after that we can have a PR with these integrations and making it production ready.

2024-09-03 11:58 UTC, Gauravjeetsingh commented
@amitojsingh gave you access.

2024-09-03 12:15 UTC, Gauravjeetsingh commented on package.json
> +    "jotai": "^2.9.3",
@gurjit03 veerji, We need to manage global state when running through the game session. Few examples:
- When we answer incorrectly, the button in footer has a different action.
- When we answer correctly, it updates the progress bar in the footer component.
- The state persists between page navigation. If we switch to another page, or even close the tab and reopen we want it to perseve the game progress. 

@amitojsingh regarding not using redux or easy-peasy (wrapper of redux), both are a complicated and heavy state management tools. Jotai is simple and adds minimal size to bundle. I also like how flexibly we can use this state without adhering to a rigid data structure. Also, found it reliable as its used by big companies like Meta, Adobe and Tiktok. 

And we can't just use react query as its good for fetching data, but is not designed for managing local UI states.

I have been loving working with it so far, Have a look:
https://jotai.org/

2024-09-03 12:17 UTC, Gauravjeetsingh commented on src/components/common/utils/updateProfile.ts
> +    console.error("Error uploading file", error);
Created an issue for this:
https://github.com/Gauravjeetsingh/gurmukhi-shabadavali/issues/5

2024-09-03 12:18 UTC, Gauravjeetsingh commented on src/components/dashboard/Dashboard.tsx
> +               to go for your next coin!
yeah, that's in plan. Was hoping to do it after session creation part. Created an issue for this
https://github.com/Gauravjeetsingh/gurmukhi-shabadavali/issues/6

2024-09-04 09:13 UTC, Gauravjeetsingh commented on src/components/game-session/Sentences.tsx
> +      <p>Examples</p>
#6

2024-09-04 09:29 UTC, Gauravjeetsingh commented on src/components/common/CustomFooter.tsx
> +  const currentSession = useAtomValue(sessionAtom);
Done, thank you! 👍

2024-09-04 09:35 UTC, merged